phonebook/config/routes.rb
Phonebook::Application.routes.draw do
  get "phone/newphone"
  get "phone/index"
  get "phone/modify/:id" => "phone#modify"
  get "phone/del/:id" => "phone#del"

  post "phone/create"
  put  "phone/updateing/:id" => "phone#updateing"
  put  "phone/destoring/:id" => "phone#destoring"

end

phonebook/app/models/pbook.rb
class Pbook < ActiveRecord::Base
  attr_accessible :birthday, :name, :phone
end

phonebook/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

phonebook/app/controllers/phone_controller.rb
class PhoneController < ApplicationController
  def index
	@phones = Pbook.all
  end

  def newphone
	@pbook = Pbook.new
  end

  def create
	@pbook = Pbook.new(params[:pbook])
        @pbook.save
	redirect_to :action =>"index"
  end

  def modify
	@pbook = Pbook.find(params[:id])
  end

  def updateing
	@pbook = Pbook.find(params[:id])
	@pbook.update_attributes(params[:pbook])

	redirect_to :action =>"index"
  end

  def del
	@pbook = Pbook.find(params[:id])
	@pbook.destroy

	redirect_to :action =>"index"
  end
end

phonebook/app/helpers/application_helper.rb
module ApplicationHelper
end

phonebook/app/helpers/phone_helper.rb
module PhoneHelper
end

phonebook/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Phonebook</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

phonebook/app/views/phone/index.html.erb
<h1>Phone#index</h1>
<table border="0" >
  <tr>
   <td>Name</td><td>Phone Number</td><td>Birthday</td>
  </tr>
<% @phones.each do |p| %>
  <tr>
   <td><%=p.name %></td><td><%=p.phone%></td><td><%=p.birthday%></td>
   <td>
	<%= link_to "edit" , :action =>"modify" , :id => p%> /
	<%= link_to "del" , :action => "del", :id => p%>
   </td>
  </tr>
<% end%>
</table>
<p><%= link_to "add new phone number" , phone_newphone_path %></p>

phonebook/app/views/phone/modify.html.erb
<h1>Modify the phone number</h1>
<%= form_for @pbook , :url =>{:controller => "phone" , :action => "updateing", :id => @pbook} do |f|%>
<div class="field">
	<%= f.label :name %><br />
	<%= f.text_field :name %>
</div>
<div class="field">
        <%= f.label :phone %><br />
        <%= f.text_field :phone %>
</div>
<div class="field">
        <%= f.label :birthday %><br />
        <%= f.text_field :birthday %>
</div>
  <div class="actions">
	<%= f.submit %>
  </div>
<%end%>
<p><%= link_to 'Back', phone_index_path %></p>

phonebook/app/views/phone/newphone.html.erb
<h1>Add a new phone number</h1>
<%= form_for @pbook , :url => {:controller => "phone", :action => "create"} do |f|%>
<div class="field">
  <%= f.label :name %><br />
  <%= f.text_field :name %>
</div>
<div class="field">
  <%= f.label :phone %><br />
  <%= f.text_field :phone %>
</div>
<div class="field">
  <%= f.label :birthday %><br />
  <%= f.text_field :birthday %>
</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<p><%= link_to 'Back', phone_index_path %></p>